AndroidEarlyBirdy/EarlyBirdy

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt, app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanAdapter.kt, app/src/main/java/com/example/earlybirdy/data/Todo.kt, app/src/main/res/drawable/ic_create_plan_add_todo.xml, app/src/main/res/drawable/ic_create_plan_delete.xml, app/src/main/res/drawable/item_todo.xml, app/src/main/res/layout/activity_create_plan.xml, app/src/main/res/layout/item_todo.xml, gradle.properties, settings.gradle
1. Create Plan Activity UI 작업
2. Recyclerview Adapter 및 item 생성
=> Create Plan Activity Ui 작업 및 recyclerview 작업

app/src/main/AndroidManifest.xml, app/src/main/res/layout/fragment_my_page.xml, app/src/main/res/layout/item_todo.xml
1. AndroidManifest 수정 사항 원상 복구
2. item layout 오류 fix
=> fix : AndroidManifest 변경 및 item layout 오류 fix

app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt, app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
1. 로그인 회원가입 빈칸 에러 메시지 항목별 출력으로 수정
=> fix: 로그인 회원가입 빈칸 에러 메시지 항목별 출력으로 수정

app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt, app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt, app/src/main/res/layout/activity_item_setting.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_setting.xml, app/src/main/res/layout/activity_signin.xml, app/src/main/res/layout/activity_signup.xml, app/src/main/res/layout/fragment_my_page.xml, app/src/main/res/layout/item_todo.xml
1. 앱 실행 시 로그인 회원가입 페이지에서 로그인 여부 체크 기능 추가
=> feat: 앱 실행 시 로그인 회원가입 페이지에서 로그인 여부 체크 기능 추가

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/earlybirdy/main/MainActivity.kt, app/src/main/java/com/example/earlybirdy/main/MainTabs.kt, app/src/main/java/com/example/earlybirdy/main/MainViewPagerAdapter.kt, app/src/main/java/com/example/earlybirdy/main/SplashActivity.kt, app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt, app/src/main/res/layout/activity_main.xml
1.  main package 정리
2. MainActivity Refactor
3. SplashActivity Refactor
=> MainActivity Refactor / Splash Activity Refactor

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/earlybirdy/board/BoardFragment.kt, app/src/main/java/com/example/earlybirdy/sendemail/SendEmailActivity.kt, app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt, app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt, app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt, app/src/main/res/layout/activity_reset_password.xml, app/src/main/res/layout/activity_send_email.xml
1. 로그인이 안되어있을 경우 사용자의 이메일로 메일을 보내 비밀번호 재설정 하는 기능 추가
=> 로그인이 안되어있을 경우 비밀번호 재설정 기능 추가

app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt, app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt, app/src/main/res/drawable/bg_calendar_today.xml
1. CreatePlanAcitivty 오늘 날짜 Decoration 추가
=> CreatePlanActivity 오늘 날짜 Decoration 기능 추가

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt, app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanDialog.kt
1. Dialog 에서 Todo 추가하면 CreatePlanActivity 에 반영
=> CreatePlanActivity Todo 추가

app/src/main/res/layout/activity_alarm.xml, app/src/main/res/layout/activity_create_plan.xml, app/src/main/res/layout/activity_edit_profile.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_setting.xml, app/src/main/res/layout/activity_signin.xml, app/src/main/res/layout/activity_signup.xml, app/src/main/res/layout/fragment_board.xml, app/src/main/res/layout/setting_detail.xml
=> ui : 전반적인 layout 그라데이션 배경 작업

app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
=> HomeFragment 알람 시간 적용 

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt, app/src/main/res/layout/activity_setting.xml, app/src/main/res/values/strings.xml
1. Setting Activity 알림설정 기능 추가
=> feat : SettingActivity 알림설정 기능 추가

app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt, app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanAdapter.kt, app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanDialog.kt, app/src/main/java/com/example/earlybirdy/data/Todo.kt
1. Create, Update, Delete Firebase 연동
=> feature : Create, Update, Delete 데이터 베이스 연동

app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt, app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanAdapter.kt, app/src/main/java/com/example/earlybirdy/data/Todo.kt, app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt, app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt
1. Create 내역 사라지는 버그 해결
2. Delete 이후 Todo 겹쳐 보이는 버그 해결
3. Update 로직 수정
=> CreateTodoActivity 프론트엔드 상 Create / Delete / Update 버그 해결

app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt, app/src/main/java/com/example/earlybirdy/dto/TodoDto.kt
=> CreateTodoActivity Firebase 데이터 로드 기능 구현

app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt, app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt, app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt, app/src/main/res/layout/fragment_my_page.xml
1. 마이페이지에서 localExp 값에 따라 경험치 량과 프로그레스 바, 레벨 값 변화
=> 마이페이지에서 localExp 값에 따라 경험치 량과 프로그레스 바, 레벨 값 변화

app/src/main/java/com/example/earlybirdy/create_plan/CreateFailDialog.kt, app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt, app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanAdapter.kt, app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanDialog.kt, app/src/main/java/com/example/earlybirdy/dto/UserDto.kt, app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt, app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt, app/src/main/res/layout/activity_create_plan.xml, app/src/main/res/layout/dialog_fail_to_add.xml, app/src/main/res/layout/item_todo.xml
1.하루 3개 이상 Todo 설정 불가
2.스크롤 문제 해결
3.체크박스 제거
4.뒤로가기 버튼 생성
5.예전 날짜 Todo 생성 불가 기능
6. 회원가입 시 경험치 추가
=> Create Todo 기능 수정 / 회원가입 시 경험치 추가

app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivityDialog.kt
=> feature: EditProfileActivity

app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt, app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt, app/src/main/res/layout/fragment_my_page.xml
1. MyPageFragment 아이디 중복 오류 수정
2. SettingDetail 오류 수정
=> MyPageFragment 오류 수정 및 SettingDetail 오류 수정

app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt, app/src/main/java/com/example/earlybirdy/dto/AttendanceDto.kt, app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt, app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt, app/src/main/res/layout/fragment_my_page.xml
=> MyPageFragment Firebase 연동하여 데이터 출력

app/src/main/AndroidManifest.xml, app/src/main/res/values-night/themes.xml
=> feature: 가로모드,다크모드 막기

app/src/main/java/com/example/earlybirdy/alarm/AlarmActivity.kt
1. 타임피커의 시간이 7시가 되면 00분으로 분을 고정하는 기능 추가
=> 타임피커의 시간이 7시가 되면 00분으로 분을 고정하는 기능 추가

app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt, app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt, app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt, app/src/main/java/com/example/earlybirdy/my_page/MyPageViewModel.kt, app/src/main/java/com/example/earlybirdy/my_page/MyPageViewModelFactory.kt, app/src/main/java/com/example/earlybirdy/repository/UserRepository.kt, app/src/main/java/com/example/earlybirdy/repository/UserRepositoryImpl.kt, app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt, app/src/main/res/drawable/ic_edit_profile.xml, app/src/main/res/layout/fragment_my_page.xml
1. 달력 Touch 안되게 수정하기
2. Profile Id에 따른 프로필 사진 변경
3. 내 정보 수정 페이지 이동 구현
4. ViewModel 수정
=> MyPageFragment 수정

app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt, app/src/main/res/layout/activity_setting.xml
1. 설정 액티비티 고객지원 버튼 클릭시 구글폼으로 이동
2. 화면이 작은 디바이스를 위한 항목 간격 수정
=> ui/설정 액티비티 고객지원 버튼 수정, 항목간격 수정

app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivity.kt
=> fix: 비밀번호 수정

app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt, app/src/main/java/com/example/earlybirdy/my_page/MyPageViewModel.kt
1. 3개였던 exp, level, maxExp 데이터 1개로 수정
=> MyPageFragment MVVM live data 수정

app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt, app/src/main/java/com/example/earlybirdy/setting/SettingCheckUserDialog.kt, app/src/main/java/com/example/earlybirdy/setting/SettingDeleteDialog.kt, app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt, app/src/main/java/com/example/earlybirdy/setting/SettingViewModel.kt, app/src/main/java/com/example/earlybirdy/util/Constants.kt, app/src/main/java/com/example/earlybirdy/util/IntentKeys.kt, app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
1. SettingActivity 코드 리팩토링
2. ViewModel 추가 후 signout 이동
=> SettingActivity 리팩토링 및 ViewModel 추가

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/earlybirdy/main/SplashActivity.kt, app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt, app/src/main/java/com/example/earlybirdy/signin/SignInActivity.kt, app/src/main/java/com/example/earlybirdy/signin/SignInViewModel.kt, app/src/main/java/com/example/earlybirdy/signin/sendemail/SendEmailActivity.kt, app/src/main/java/com/example/earlybirdy/signin/sendemail/SendEmailViewModel.kt, app/src/main/java/com/example/earlybirdy/util/IntentKeys.kt, app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt, app/src/main/res/layout/activity_send_email.xml, app/src/main/res/layout/activity_signin.xml
1. SendEmailActivity ViewModel 적용
2. Signin 함수 Class 명, 함수 명 변경
=> SendEmailActivity ViewModel 적용

app/src/main/java/com/example/earlybirdy/home/ExpDialog.kt, app/src/main/res/drawable/ic_dialog_share.xml, app/src/main/res/layout/dialog_exp.xml
1. ExpDialog UI
2. ExpDialog 클래스파일
=> Design : ExpDialog

app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt, app/src/main/res/drawable/btn_leftarrow.xml, app/src/main/res/drawable/btn_rightarrow.xml, app/src/main/res/layout/fragment_home.xml
1. 목표 리스트에 화살표 추가 완료했습니다.
HomeFragment.kt
close #175
=> 목표 리스트에 화살표 기능 추가

app/src/main/java/com/example/earlybirdy/my_page/BackgroundSpan.kt, app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt, app/src/main/res/drawable/bg_calendar_date1.xml, app/src/main/res/drawable/bg_calendar_date2.xml, app/src/main/res/drawable/bg_calendar_date3.xml, app/src/main/res/drawable/bg_calendar_date4.xml, app/src/main/res/values/colors.xml
1. 커스텀 달력 background 수정 완료했습니다.
##주요 변동 파일
1. MypageFragment.kt
close #179
=> 커스텀 달력 background 수정

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/earlybirdy/RankingFragment.kt, app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt, app/src/main/java/com/example/earlybirdy/home/WeatherData.kt, app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt, app/src/main/res/drawable/ic_glassbackground.xml, app/src/main/res/drawable/ic_topbackground.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/values/strings.xml
1. 홈 프레그먼트 상단 명언 구현
2. 홈 프레그먼트 상단 날씨 api 기능 구현
+ HomeFragment.kt
+ fragment_home.xml
+ strings.xml
+ WeatherData.kt
=> [Homefragment] 명언 및 날씨 api 구현

app/src/main/java/com/example/earlybirdy/RankingFragment.kt, app/src/main/java/com/example/earlybirdy/dto/AttendanceDto.kt, app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt, app/src/main/java/com/example/earlybirdy/home/WeatherData.kt, app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
1. 마이 프레그먼트 auth.uid 오류 fix
2. 홈 프레그먼트 상단 명언 구현
3. 명언 글자수 제한
4. 랭킹보드 오류 해결
5. HomeFragment 프로그래스바 오류 수정
##주요 변동 파일
+ RankingFragment.kt
+ AttendanceDto.kt
+ HomeFragment.kt
+ MyPageFragment.kt
=> 마이 프레그먼트 오류 수정 및 상단 명언 구현

app/build.gradle, app/src/main/java/com/example/earlybirdy/board/board_main/BoardAdapter.kt, app/src/main/java/com/example/earlybirdy/board/board_main/BoardFragment.kt, app/src/main/java/com/example/earlybirdy/board/board_read/BoardReadActivity.kt, app/src/main/java/com/example/earlybirdy/board/board_write/BoardWriteActivity.kt, app/src/main/java/com/example/earlybirdy/dto/BoardDto.kt, app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt, app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt, app/src/main/res/layout/activity_board_read.xml, app/src/main/res/layout/activity_board_write.xml, app/src/main/res/layout/item_board.xml
1. 사진 첨부 및 작성 시간 저장 기능 추가
- BoardFragment.kt
- BoardWriteAcitivity.kt
- BoardReadAcitivity.kt
close #182
=> [BoardFragment] 게시판 추가 기능 구현

app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
1. Plan 삭제 시 check 여부 판단하여 경험치 삭제 구현
=> [CreatePlanActivity] Plan 삭제 시 경험치 삭제 구현

app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
1. 달력 색상 오류 수정하기 
##주요 변동 파일
+ MyPageFragment.kt
close #196
=> 달력 색상 오류 수정

app/src/main/java/com/example/earlybirdy/board/board_main/BoardAdapter.kt, app/src/main/java/com/example/earlybirdy/board/board_main/BoardFragment.kt, app/src/main/java/com/example/earlybirdy/board/board_read/BoardReadActivity.kt, app/src/main/java/com/example/earlybirdy/board/board_write/BoardWriteActivity.kt, app/src/main/java/com/example/earlybirdy/dto/BoardDto.kt, app/src/main/res/values/strings.xml
1. Firebase Storage 활용 사진 업로드 다운로드 구현
- BoardDto 변경
- Storage 활용
- 갤러리 관련 코드 수정
=> [Board] Firebase Storage 활용 사진 업로드, 다운로드 구현

app/src/main/java/com/example/earlybirdy/alarm/AlarmActivity.kt, app/src/main/java/com/example/earlybirdy/alarm/AlarmReceiver.kt, app/src/main/java/com/example/earlybirdy/main/SplashActivity.kt, app/src/main/java/com/example/earlybirdy/sealedclass/SigninNavigation.kt, app/src/main/java/com/example/earlybirdy/setting/SettingCheckUserDialog.kt, app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt, app/src/main/java/com/example/earlybirdy/signin/SigninViewModel.kt
1. 알림 액티비티 소리/진동 끄기 쉐어드 프레퍼런스 삭제 및 로그 삭제
2. 로그인 페이지에서 사용자의 로그인 여부 확인 함수를 스플래시 화면으로 이동
3. 회원탈퇴 수정은 보류
=> 알림 및 기타 기능 수정

app/src/main/java/com/example/earlybirdy/board/board_main/BoardAdapter.kt, app/src/main/java/com/example/earlybirdy/board/board_read/BoardReadActivity.kt, app/src/main/java/com/example/earlybirdy/board/board_write/BoardWriteActivity.kt
1. RecyclerView 사진 출력
2. 사진 수정 기능 구현
=> Board 사진 업로드 기능 구현

app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt, app/src/main/java/com/example/earlybirdy/util/Constants.kt
//구현기능
1. 오픈라이선스 구글폼 연결
2. 약관 구글폼 연결
//주요변경파일
1. SettingActivit
2. Constants
//
close #209
=> 라이선스, 약관 구글폼 연동

app/src/main/java/com/nbcproject/earlybirdy/my_page/MyPageFragment.kt, app/src/main/java/com/nbcproject/earlybirdy/setting/SettingCheckUserDialog.kt
=> 회원탈퇴 오류 수정

app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardFragment.kt
1. 게시판에서 내글보기랑 전체글보기에서 새로고침 버튼을 눌렀을 때 무조건 내글보기로 가는 문제 수정
=> 게시판에서 내글보기랑 전체글보기에서 새로고침 버튼을 눌렀을 때 무조건 내글보기로 가는 문제 수정

app/src/main/java/com/nbcproject/earlybirdy/repository/AuthRepository.kt, app/src/main/java/com/nbcproject/earlybirdy/repository/AuthRepositoryImpl.kt, app/src/main/java/com/nbcproject/earlybirdy/setting/SettingActivity.kt, app/src/main/java/com/nbcproject/earlybirdy/setting/dialog/SettingCheckUserDialog.kt, app/src/main/java/com/nbcproject/earlybirdy/setting/dialog/SettingDeleteDialog.kt, app/src/main/java/com/nbcproject/earlybirdy/setting/viewmodel/SettingViewModel.kt, app/src/main/java/com/nbcproject/earlybirdy/setting/viewmodel/SettingViewModelFactory.kt, app/src/main/res/values/strings.xml
1. SettingActivity 리팩토링
2. AuthRepository 추가 후 Signout 이동
=> [SettingActivty] Refactor

app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt, app/src/main/java/com/nbcproject/earlybirdy/util/Constants.kt, app/src/main/res/layout/activity_board_read.xml
1. 게시글 보기 페이지에 신고하기 버튼 눌엇을 경우 구글폼으로 이동하는 기능 추가
=> 게시글 보기 페이지 신고하기 기능 추가

app/src/main/AndroidManifest.xml
=> [AndroidManifest] AndroidManifest 오류 Fix

app/src/main/java/com/nbcproject/earlybirdy/board/board_write/BoardWriteActivity.kt, app/src/main/java/com/nbcproject/earlybirdy/sign/signup/SignupActivity.kt, app/src/main/res/layout/activity_board_read.xml, app/src/main/res/layout/activity_board_write.xml, app/src/main/res/layout/activity_setting_login_dialog.xml
1. 게시글 읽기/보기 페이지 ui 위젯 1차 정리
2. 갤러리 접근 권한 READ_MEDIA_IMAGES 추가
3. 6미만의 비밀번호를 입력했을 경우 회원가입이 안되는 경우 에외처리 추가
=> 게시판 레이아웃 수정 및 추가 기능 수정

app/src/main/res/layout/fragment_home.xml
1. 프로그레스바 ui 수정 완료했습니다.
+ fragment_home.xml
=> 프로그레스바 ui 수정

app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardAdapter.kt, app/src/main/java/com/nbcproject/earlybirdy/sign/signup/SignupActivity.kt
=> [BoardFragment] 댓글 수 출력 기능 구현

app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt, app/src/main/java/com/nbcproject/earlybirdy/board/board_write/BoardWriteActivity.kt, app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileActivity.kt, app/src/main/java/com/nbcproject/earlybirdy/main/MainActivity.kt, app/src/main/java/com/nbcproject/earlybirdy/my_page/MyPageFragment.kt, app/src/main/res/layout/activity_signup.xml, app/src/main/res/layout/activity_signup_dialog.xml, app/src/main/res/layout/fragment_my_page.xml
1. 인터넷 Dialog 수정
2. 기본 프로필 사진 변경
=> 인터넷 Dialog 수정 및 기본 프로필 사진 변경

app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardAdapter.kt, app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt
1. 게시글 사진이 없을 때 대체 이미지 대표로고로 수정
=> 게시글 사진이 없을 때 대체 이미지 대표로고로 수정

app/src/main/java/com/nbcproject/earlybirdy/setting/SettingActivity.kt
1. Setting Activity 구글폼 이동 함수 수정
=> SettingActivity 추가 수정 사항 반영

app/src/main/java/com/nbcproject/earlybirdy/sign/sendemail/SendEmailActivity.kt
=> SendEmailActivity 재 Refactoring

app/src/main/java/com/nbcproject/earlybirdy/board/board_write/BoardWriteActivity.kt, app/src/main/java/com/nbcproject/earlybirdy/data/Alarm.kt, app/src/main/java/com/nbcproject/earlybirdy/data/BoardData.kt
1. 사용 안하는 Data Class 삭제
2. 미사용 DTO 삭제
=> Data Class 및 DTO 정리

app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardAdapter.kt, app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardFragment.kt, app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt, app/src/main/java/com/nbcproject/earlybirdy/board/board_read/CommentAdapter.kt, app/src/main/java/com/nbcproject/earlybirdy/board/board_write/BoardWriteActivity.kt, app/src/main/res/values/strings.xml
1. Board Fragment 및 Activity, Adapter 리팩토링
=> BoardFragment, 관련 Activity 리팩토링

app/src/main/res/layout/fragment_home.xml
=> 홈 프레그먼트 이전 ui로 수정

app/src/main/java/com/nbcproject/earlybirdy/create_plan/CreatePlanActivity.kt, app/src/main/java/com/nbcproject/earlybirdy/create_plan/dialog/CreateFailDialog.kt, app/src/main/java/com/nbcproject/earlybirdy/create_plan/dialog/CreatePlanDialog.kt, app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileActivity.kt, app/src/main/java/com/nbcproject/earlybirdy/edit_profile/dialog/EditProfileActivityDialog.kt, app/src/main/java/com/nbcproject/earlybirdy/edit_profile/dialog/EditProfileDialog.kt, app/src/main/java/com/nbcproject/earlybirdy/home/HomeFragment.kt, app/src/main/java/com/nbcproject/earlybirdy/my_page/MyPageFragment.kt, app/src/main/java/com/nbcproject/earlybirdy/my_page/viewmodel/MyPageViewModel.kt, app/src/main/java/com/nbcproject/earlybirdy/my_page/viewmodel/MyPageViewModelFactory.kt, app/src/main/java/com/nbcproject/earlybirdy/resetpassword/ResetPasswordActivity.kt
1. HomeFragment Null point Exception 해결
=> Hoem Fragment Nullpoint Exception 해결

app/src/main/java/com/nbcproject/earlybirdy/board/board_write/BoardWriteActivity.kt, app/src/main/java/com/nbcproject/earlybirdy/sign/sendemail/SendEmailActivity.kt
1. SendEmailActivity 이메일 입력 공백 시 페이지 이동 문제 수정
2. Board 작성 시 버튼 여러 번 클릭 시 중복 생성 문제 해결
=> SendEmailActivity 이메일 입력 공백 시 발생 문제 해결 / Board 작성 시 버튼 여러 번 클릭 시 글 중복 생성 문제 해결

app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt
=> Board 댓글 작성 시 즉시 반영
